Config = {}

Config.Job = 'mechanic'

Config.Items = {
label = "Mechanic Shop",
    slots = 7,
    items = {
        [1] = {
            name = "engine0",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "engine1",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "engine2",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "engine3",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "engine4",
            price = 0,
            amount = 2,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "brake0",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "brake1",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "brake2",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "brake3",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "transmission0",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "transmission1",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "transmission2",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "transmission3",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "suspension0",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "suspension1",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "suspension2",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "suspension3",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "turbo0",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "turbo1",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 19,
        },
    }
}

